#!/bin/bash

minDedup=85
function cleanUp {
 rm -rf testDir test.index
}

function runVDOEstimator {
  sync
  ./vdoestimator --index test.index $* ./testDir
}

cleanUp
mkdir testDir
dd if=/dev/zero ibs=4k count=22 > testDir/data 2>/dev/null
dedupPercent=`runVDOEstimator | grep 'Dedupe Percentage' | awk '{print $3}' | sed 's/%//'`
dedupPercent=${dedupPercent/\.*}
if [ $dedupPercent -lt $minDedup ]; then
  echo Dedup too low: $dedupPercent
  exit 1  
else
  echo succeed: $dedupPercent
fi

dedup1=$dedupPercent

cleanUp
mkdir testDir
dd if=/dev/zero ibs=4k count=22 2>/dev/null | tr "\000" "\377" > testDir/data 
dedupPercent=`runVDOEstimator | grep 'Dedupe Percentage' | awk '{print $3}' | sed 's/%//'`
dedupPercent=${dedupPercent/\.*}
if [ $dedupPercent -lt $minDedup ]; then
  echo Dedup too low: $dedupPercent
  exit 1
else
  echo succeed: $dedupPercent
fi
dedup2=$dedupPercent

if [ $dedup1 != $dedup2 ]; then
  echo Dedup rate should be the same for the first two tests.
  exit 1;
fi
  
cleanUp
mkdir testDir
dd if=/dev/zero ibs=4k count=11 >  testDir/data 2>/dev/null
dd if=/dev/zero ibs=4k count=11 2>/dev/null | tr "\000" "\377" >> testDir/data 2>/dev/null
dedupPercent=`runVDOEstimator | grep 'Dedupe Percentage' | awk '{print $3}' | sed 's/%//'`
dedupPercent=${dedupPercent/\.*}
if [ $dedupPercent -lt $minDedup ]; then
  echo Dedup too low: $dedupPercent
  exit 1  
else
  echo succeed: $dedupPercent
fi

cleanUp
mkdir testDir
dd if=/dev/urandom of=testDir/file1 bs=4K count=1 status=none
cp testDir/file1 testDir/file2
cp testDir/file1 testDir/file3
cp testDir/file1 testDir/file4
result=`runVDOEstimator --dedupeOnly`
if ! echo "$result" | grep -q -e "Total Bytes Used: 4096"; then
  echo "expected 'Total Bytes Used: 4096'"
  exit 1
fi
if ! echo "$result" | grep -q -e "Total Percent Saved: 75.000%"; then
  echo "expected 'Total Percent Saved: 75.000%'"
  exit 1
fi

echo "dedupeOnly test succeeded"

cleanUp

exit 0
